// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_communication.cpp"
#include "EWIEGA46WW/moc_robotgraplord.cpp"
#include "EWIEGA46WW/moc_robotplayhand.cpp"
#include "EWIEGA46WW/moc_taskqueue.cpp"
